# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client /server'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: dependency
      prefix-development: dependency
    open-pull-requests-limit: 99
