# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps)
    open-pull-requests-limit: 99

  - package-ecosystem: 'deps'
    directory: '/server/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps)
    open-pull-requests-limit: 99
