version: '3.7'

services:
    mongodb_easy_shop:
        image: mongo:latest
        container_name: mongodb_easy_shop
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: easy_shop
        ports:
            - 27017:27017
        volumes:
            - ./db/:/data/db